// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package ftpserver.proto;

public final class MessagesProtos {
	private static final com.google.protobuf.Descriptors.Descriptor
			internal_static_proto_ClientRequest_descriptor;
	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_proto_ClientRequest_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.Descriptor
			internal_static_proto_ClientRequest_Socket_descriptor;
	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_proto_ClientRequest_Socket_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.Descriptor
			internal_static_proto_ServerResponse_descriptor;
	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_proto_ServerResponse_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.FileDescriptor
			descriptor;

	static {
		java.lang.String[] descriptorData = {
				"\n\016messages.proto\022\005proto\"\325\001\n\rClientReques" +
						"t\022.\n\004type\030\001 \001(\0162 .proto.ClientRequest.Me" +
						"ssageType\022\013\n\003arg\030\002 \001(\t\022)\n\004sock\030\003 \001(\0132\033.p" +
						"roto.ClientRequest.Socket\0323\n\006Socket\022\017\n\007a" +
						"ddress\030\001 \001(\t\022\014\n\004port\030\002 \001(\t\022\n\n\002id\030\003 \001(\t\"\'" +
						"\n\013MessageType\022\006\n\002LS\020\000\022\006\n\002UP\020\001\022\010\n\004DOWN\020\002\"" +
						"+\n\016ServerResponse\022\013\n\003ack\030\001 \001(\010\022\014\n\004args\030\002" +
						" \003(\tB\020B\016MessagesProtosb\006proto3"
		};
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
				new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
					public com.google.protobuf.ExtensionRegistry assignDescriptors(
							com.google.protobuf.Descriptors.FileDescriptor root) {
						descriptor = root;
						return null;
					}
				};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[]{
						}, assigner);
		internal_static_proto_ClientRequest_descriptor =
				getDescriptor().getMessageTypes().get(0);
		internal_static_proto_ClientRequest_fieldAccessorTable = new
				com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_proto_ClientRequest_descriptor,
				new java.lang.String[]{"Type", "Arg", "Sock",});
		internal_static_proto_ClientRequest_Socket_descriptor =
				internal_static_proto_ClientRequest_descriptor.getNestedTypes().get(0);
		internal_static_proto_ClientRequest_Socket_fieldAccessorTable = new
				com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_proto_ClientRequest_Socket_descriptor,
				new java.lang.String[]{"Address", "Port", "Id",});
		internal_static_proto_ServerResponse_descriptor =
				getDescriptor().getMessageTypes().get(1);
		internal_static_proto_ServerResponse_fieldAccessorTable = new
				com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_proto_ServerResponse_descriptor,
				new java.lang.String[]{"Ack", "Args",});
	}

	private MessagesProtos() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions(
				(com.google.protobuf.ExtensionRegistryLite) registry);
	}

	public static com.google.protobuf.Descriptors.FileDescriptor
	getDescriptor() {
		return descriptor;
	}

	public interface ClientRequestOrBuilder extends
			// @@protoc_insertion_point(interface_extends:proto.ClientRequest)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>.proto.ClientRequest.MessageType type = 1;</code>
		 */
		int getTypeValue();

		/**
		 * <code>.proto.ClientRequest.MessageType type = 1;</code>
		 */
		proto.MessagesProtos.ClientRequest.MessageType getType();

		/**
		 * <code>string arg = 2;</code>
		 */
		java.lang.String getArg();

		/**
		 * <code>string arg = 2;</code>
		 */
		com.google.protobuf.ByteString
		getArgBytes();

		/**
		 * <code>.proto.ClientRequest.Socket sock = 3;</code>
		 */
		boolean hasSock();

		/**
		 * <code>.proto.ClientRequest.Socket sock = 3;</code>
		 */
		proto.MessagesProtos.ClientRequest.Socket getSock();

		/**
		 * <code>.proto.ClientRequest.Socket sock = 3;</code>
		 */
		proto.MessagesProtos.ClientRequest.SocketOrBuilder getSockOrBuilder();
	}

	public interface ServerResponseOrBuilder extends
			// @@protoc_insertion_point(interface_extends:proto.ServerResponse)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>bool ack = 1;</code>
		 */
		boolean getAck();

		/**
		 * <code>repeated string args = 2;</code>
		 */
		java.util.List<java.lang.String>
		getArgsList();

		/**
		 * <code>repeated string args = 2;</code>
		 */
		int getArgsCount();

		/**
		 * <code>repeated string args = 2;</code>
		 */
		java.lang.String getArgs(int index);

		/**
		 * <code>repeated string args = 2;</code>
		 */
		com.google.protobuf.ByteString
		getArgsBytes(int index);
	}

	/**
	 * Protobuf type {@code proto.ClientRequest}
	 */
	public static final class ClientRequest extends
			com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:proto.ClientRequest)
			ClientRequestOrBuilder {
		public static final int TYPE_FIELD_NUMBER = 1;
		public static final int ARG_FIELD_NUMBER = 2;
		public static final int SOCK_FIELD_NUMBER = 3;
		private static final long serialVersionUID = 0L;
		// @@protoc_insertion_point(class_scope:proto.ClientRequest)
		private static final proto.MessagesProtos.ClientRequest DEFAULT_INSTANCE;
		private static final com.google.protobuf.Parser<ClientRequest>
				PARSER = new com.google.protobuf.AbstractParser<ClientRequest>() {
			@java.lang.Override
			public ClientRequest parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new ClientRequest(input, extensionRegistry);
			}
		};

		static {
			DEFAULT_INSTANCE = new proto.MessagesProtos.ClientRequest();
		}

		private int type_;
		private volatile java.lang.Object arg_;
		private proto.MessagesProtos.ClientRequest.Socket sock_;
		private byte memoizedIsInitialized = -1;

		// Use ClientRequest.newBuilder() to construct.
		private ClientRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private ClientRequest() {
			type_ = 0;
			arg_ = "";
		}

		private ClientRequest(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new java.lang.NullPointerException();
			}
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields =
					com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						case 8: {
							int rawValue = input.readEnum();

							type_ = rawValue;
							break;
						}
						case 18: {
							java.lang.String s = input.readStringRequireUtf8();

							arg_ = s;
							break;
						}
						case 26: {
							proto.MessagesProtos.ClientRequest.Socket.Builder subBuilder = null;
							if (sock_ != null) {
								subBuilder = sock_.toBuilder();
							}
							sock_ = input.readMessage(proto.MessagesProtos.ClientRequest.Socket.parser(), extensionRegistry);
							if (subBuilder != null) {
								subBuilder.mergeFrom(sock_);
								sock_ = subBuilder.buildPartial();
							}

							break;
						}
						default: {
							if (!parseUnknownFieldProto3(
									input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return proto.MessagesProtos.internal_static_proto_ClientRequest_descriptor;
		}

		public static proto.MessagesProtos.ClientRequest parseFrom(
				java.nio.ByteBuffer data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static proto.MessagesProtos.ClientRequest parseFrom(
				java.nio.ByteBuffer data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static proto.MessagesProtos.ClientRequest parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static proto.MessagesProtos.ClientRequest parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static proto.MessagesProtos.ClientRequest parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static proto.MessagesProtos.ClientRequest parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static proto.MessagesProtos.ClientRequest parseFrom(java.io.InputStream input) {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static proto.MessagesProtos.ClientRequest parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static proto.MessagesProtos.ClientRequest parseDelimitedFrom(java.io.InputStream input) {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input);
		}

		public static proto.MessagesProtos.ClientRequest parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static proto.MessagesProtos.ClientRequest parseFrom(
				com.google.protobuf.CodedInputStream input) {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static proto.MessagesProtos.ClientRequest parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(proto.MessagesProtos.ClientRequest prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		public static proto.MessagesProtos.ClientRequest getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		public static com.google.protobuf.Parser<ClientRequest> parser() {
			return PARSER;
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet
		getUnknownFields() {
			return this.unknownFields;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
		internalGetFieldAccessorTable() {
			return proto.MessagesProtos.internal_static_proto_ClientRequest_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							proto.MessagesProtos.ClientRequest.class, proto.MessagesProtos.ClientRequest.Builder.class);
		}

		/**
		 * <code>.proto.ClientRequest.MessageType type = 1;</code>
		 */
		public int getTypeValue() {
			return type_;
		}

		/**
		 * <code>.proto.ClientRequest.MessageType type = 1;</code>
		 */
		public proto.MessagesProtos.ClientRequest.MessageType getType() {
			@SuppressWarnings("deprecation")
			proto.MessagesProtos.ClientRequest.MessageType result = proto.MessagesProtos.ClientRequest.MessageType.valueOf(type_);
			return result == null ? proto.MessagesProtos.ClientRequest.MessageType.UNRECOGNIZED : result;
		}

		/**
		 * <code>string arg = 2;</code>
		 */
		public java.lang.String getArg() {
			java.lang.Object ref = arg_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				arg_ = s;
				return s;
			}
		}

		/**
		 * <code>string arg = 2;</code>
		 */
		public com.google.protobuf.ByteString
		getArgBytes() {
			java.lang.Object ref = arg_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(java.lang.String) ref);
				arg_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>.proto.ClientRequest.Socket sock = 3;</code>
		 */
		public boolean hasSock() {
			return sock_ != null;
		}

		/**
		 * <code>.proto.ClientRequest.Socket sock = 3;</code>
		 */
		public proto.MessagesProtos.ClientRequest.Socket getSock() {
			return sock_ == null ? proto.MessagesProtos.ClientRequest.Socket.getDefaultInstance() : sock_;
		}

		/**
		 * <code>.proto.ClientRequest.Socket sock = 3;</code>
		 */
		public proto.MessagesProtos.ClientRequest.SocketOrBuilder getSockOrBuilder() {
			return getSock();
		}

		@java.lang.Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1) return true;
			if (isInitialized == 0) return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@java.lang.Override
		public void writeTo(com.google.protobuf.CodedOutputStream output) {
			if (type_ != proto.MessagesProtos.ClientRequest.MessageType.LS.getNumber()) {
				output.writeEnum(1, type_);
			}
			if (!getArgBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 2, arg_);
			}
			if (sock_ != null) {
				output.writeMessage(3, getSock());
			}
			unknownFields.writeTo(output);
		}

		@java.lang.Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1) return size;

			size = 0;
			if (type_ != proto.MessagesProtos.ClientRequest.MessageType.LS.getNumber()) {
				size += com.google.protobuf.CodedOutputStream
						.computeEnumSize(1, type_);
			}
			if (!getArgBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, arg_);
			}
			if (sock_ != null) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(3, getSock());
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof proto.MessagesProtos.ClientRequest)) {
				return super.equals(obj);
			}
			proto.MessagesProtos.ClientRequest other = (proto.MessagesProtos.ClientRequest) obj;

			boolean result = true;
			result = result && type_ == other.type_;
			result = result && getArg()
					.equals(other.getArg());
			result = result && (hasSock() == other.hasSock());
			if (hasSock()) {
				result = result && getSock()
						.equals(other.getSock());
			}
			result = result && unknownFields.equals(other.unknownFields);
			return result;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + TYPE_FIELD_NUMBER;
			hash = (53 * hash) + type_;
			hash = (37 * hash) + ARG_FIELD_NUMBER;
			hash = (53 * hash) + getArg().hashCode();
			if (hasSock()) {
				hash = (37 * hash) + SOCK_FIELD_NUMBER;
				hash = (53 * hash) + getSock().hashCode();
			}
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		@java.lang.Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		@java.lang.Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE
					? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<ClientRequest> getParserForType() {
			return PARSER;
		}

		@java.lang.Override
		public proto.MessagesProtos.ClientRequest getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

		/**
		 * Protobuf enum {@code proto.ClientRequest.MessageType}
		 */
		public enum MessageType
				implements com.google.protobuf.ProtocolMessageEnum {
			/**
			 * <code>LS = 0;</code>
			 */
			LS(0),
			/**
			 * <code>UP = 1;</code>
			 */
			UP(1),
			/**
			 * <code>DOWN = 2;</code>
			 */
			DOWN(2),
			UNRECOGNIZED(-1),
			;

			/**
			 * <code>LS = 0;</code>
			 */
			public static final int LS_VALUE = 0;
			/**
			 * <code>UP = 1;</code>
			 */
			public static final int UP_VALUE = 1;
			/**
			 * <code>DOWN = 2;</code>
			 */
			public static final int DOWN_VALUE = 2;
			private static final com.google.protobuf.Internal.EnumLiteMap<
					MessageType> internalValueMap =
					new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
						public MessageType findValueByNumber(int number) {
							return MessageType.forNumber(number);
						}
					};
			private static final MessageType[] VALUES = values();
			private final int value;

			MessageType(int value) {
				this.value = value;
			}

			/**
			 * @deprecated Use {@link #forNumber(int)} instead.
			 */
			@java.lang.Deprecated
			public static MessageType valueOf(int value) {
				return forNumber(value);
			}

			public static MessageType forNumber(int value) {
				switch (value) {
					case 0:
						return LS;
					case 1:
						return UP;
					case 2:
						return DOWN;
					default:
						return null;
				}
			}

			public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
			internalGetValueMap() {
				return internalValueMap;
			}

			public static final com.google.protobuf.Descriptors.EnumDescriptor
			getDescriptor() {
				return proto.MessagesProtos.ClientRequest.getDescriptor().getEnumTypes().get(0);
			}

			public static MessageType valueOf(
					com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
				if (desc.getType() != getDescriptor()) {
					throw new java.lang.IllegalArgumentException(
							"EnumValueDescriptor is not for this type.");
				}
				if (desc.getIndex() == -1) {
					return UNRECOGNIZED;
				}
				return VALUES[desc.getIndex()];
			}

			public final int getNumber() {
				if (this == UNRECOGNIZED) {
					throw new java.lang.IllegalArgumentException(
							"Can't get the number of an unknown enum value.");
				}
				return value;
			}

			public final com.google.protobuf.Descriptors.EnumValueDescriptor
			getValueDescriptor() {
				return getDescriptor().getValues().get(ordinal());
			}

			public final com.google.protobuf.Descriptors.EnumDescriptor
			getDescriptorForType() {
				return getDescriptor();
			}

			// @@protoc_insertion_point(enum_scope:proto.ClientRequest.MessageType)
		}

		public interface SocketOrBuilder extends
				// @@protoc_insertion_point(interface_extends:proto.ClientRequest.Socket)
				com.google.protobuf.MessageOrBuilder {

			/**
			 * <code>string address = 1;</code>
			 */
			java.lang.String getAddress();

			/**
			 * <code>string address = 1;</code>
			 */
			com.google.protobuf.ByteString
			getAddressBytes();

			/**
			 * <code>string port = 2;</code>
			 */
			java.lang.String getPort();

			/**
			 * <code>string port = 2;</code>
			 */
			com.google.protobuf.ByteString
			getPortBytes();

			/**
			 * <code>string id = 3;</code>
			 */
			java.lang.String getId();

			/**
			 * <code>string id = 3;</code>
			 */
			com.google.protobuf.ByteString
			getIdBytes();
		}

		/**
		 * Protobuf type {@code proto.ClientRequest.Socket}
		 */
		public static final class Socket extends
				com.google.protobuf.GeneratedMessageV3 implements
				// @@protoc_insertion_point(message_implements:proto.ClientRequest.Socket)
				SocketOrBuilder {
			public static final int ADDRESS_FIELD_NUMBER = 1;
			public static final int PORT_FIELD_NUMBER = 2;
			public static final int ID_FIELD_NUMBER = 3;
			private static final long serialVersionUID = 0L;
			// @@protoc_insertion_point(class_scope:proto.ClientRequest.Socket)
			private static final proto.MessagesProtos.ClientRequest.Socket DEFAULT_INSTANCE;
			private static final com.google.protobuf.Parser<Socket>
					PARSER = new com.google.protobuf.AbstractParser<Socket>() {
				@java.lang.Override
				public Socket parsePartialFrom(
						com.google.protobuf.CodedInputStream input,
						com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
					return new Socket(input, extensionRegistry);
				}
			};

			static {
				DEFAULT_INSTANCE = new proto.MessagesProtos.ClientRequest.Socket();
			}

			private volatile java.lang.Object address_;
			private volatile java.lang.Object port_;
			private volatile java.lang.Object id_;
			private byte memoizedIsInitialized = -1;

			// Use Socket.newBuilder() to construct.
			private Socket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
				super(builder);
			}

			private Socket() {
				address_ = "";
				port_ = "";
				id_ = "";
			}

			private Socket(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				this();
				if (extensionRegistry == null) {
					throw new java.lang.NullPointerException();
				}
				int mutable_bitField0_ = 0;
				com.google.protobuf.UnknownFieldSet.Builder unknownFields =
						com.google.protobuf.UnknownFieldSet.newBuilder();
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
							case 0:
								done = true;
								break;
							case 10: {
								java.lang.String s = input.readStringRequireUtf8();

								address_ = s;
								break;
							}
							case 18: {
								java.lang.String s = input.readStringRequireUtf8();

								port_ = s;
								break;
							}
							case 26: {
								java.lang.String s = input.readStringRequireUtf8();

								id_ = s;
								break;
							}
							default: {
								if (!parseUnknownFieldProto3(
										input, unknownFields, extensionRegistry, tag)) {
									done = true;
								}
								break;
							}
						}
					}
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(this);
				} catch (java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(
							e).setUnfinishedMessage(this);
				} finally {
					this.unknownFields = unknownFields.build();
					makeExtensionsImmutable();
				}
			}

			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return proto.MessagesProtos.internal_static_proto_ClientRequest_Socket_descriptor;
			}

			public static proto.MessagesProtos.ClientRequest.Socket parseFrom(
					java.nio.ByteBuffer data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static proto.MessagesProtos.ClientRequest.Socket parseFrom(
					java.nio.ByteBuffer data,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static proto.MessagesProtos.ClientRequest.Socket parseFrom(
					com.google.protobuf.ByteString data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static proto.MessagesProtos.ClientRequest.Socket parseFrom(
					com.google.protobuf.ByteString data,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static proto.MessagesProtos.ClientRequest.Socket parseFrom(byte[] data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static proto.MessagesProtos.ClientRequest.Socket parseFrom(
					byte[] data,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static proto.MessagesProtos.ClientRequest.Socket parseFrom(java.io.InputStream input) {
				return com.google.protobuf.GeneratedMessageV3
						.parseWithIOException(PARSER, input);
			}

			public static proto.MessagesProtos.ClientRequest.Socket parseFrom(
					java.io.InputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
				return com.google.protobuf.GeneratedMessageV3
						.parseWithIOException(PARSER, input, extensionRegistry);
			}

			public static proto.MessagesProtos.ClientRequest.Socket parseDelimitedFrom(java.io.InputStream input) {
				return com.google.protobuf.GeneratedMessageV3
						.parseDelimitedWithIOException(PARSER, input);
			}

			public static proto.MessagesProtos.ClientRequest.Socket parseDelimitedFrom(
					java.io.InputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
				return com.google.protobuf.GeneratedMessageV3
						.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
			}

			public static proto.MessagesProtos.ClientRequest.Socket parseFrom(
					com.google.protobuf.CodedInputStream input) {
				return com.google.protobuf.GeneratedMessageV3
						.parseWithIOException(PARSER, input);
			}

			public static proto.MessagesProtos.ClientRequest.Socket parseFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
				return com.google.protobuf.GeneratedMessageV3
						.parseWithIOException(PARSER, input, extensionRegistry);
			}

			public static Builder newBuilder() {
				return DEFAULT_INSTANCE.toBuilder();
			}

			public static Builder newBuilder(proto.MessagesProtos.ClientRequest.Socket prototype) {
				return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
			}

			public static proto.MessagesProtos.ClientRequest.Socket getDefaultInstance() {
				return DEFAULT_INSTANCE;
			}

			public static com.google.protobuf.Parser<Socket> parser() {
				return PARSER;
			}

			@java.lang.Override
			public final com.google.protobuf.UnknownFieldSet
			getUnknownFields() {
				return this.unknownFields;
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internalGetFieldAccessorTable() {
				return proto.MessagesProtos.internal_static_proto_ClientRequest_Socket_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								proto.MessagesProtos.ClientRequest.Socket.class, proto.MessagesProtos.ClientRequest.Socket.Builder.class);
			}

			/**
			 * <code>string address = 1;</code>
			 */
			public java.lang.String getAddress() {
				java.lang.Object ref = address_;
				if (ref instanceof java.lang.String) {
					return (java.lang.String) ref;
				} else {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					address_ = s;
					return s;
				}
			}

			/**
			 * <code>string address = 1;</code>
			 */
			public com.google.protobuf.ByteString
			getAddressBytes() {
				java.lang.Object ref = address_;
				if (ref instanceof java.lang.String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(java.lang.String) ref);
					address_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string port = 2;</code>
			 */
			public java.lang.String getPort() {
				java.lang.Object ref = port_;
				if (ref instanceof java.lang.String) {
					return (java.lang.String) ref;
				} else {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					port_ = s;
					return s;
				}
			}

			/**
			 * <code>string port = 2;</code>
			 */
			public com.google.protobuf.ByteString
			getPortBytes() {
				java.lang.Object ref = port_;
				if (ref instanceof java.lang.String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(java.lang.String) ref);
					port_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string id = 3;</code>
			 */
			public java.lang.String getId() {
				java.lang.Object ref = id_;
				if (ref instanceof java.lang.String) {
					return (java.lang.String) ref;
				} else {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					id_ = s;
					return s;
				}
			}

			/**
			 * <code>string id = 3;</code>
			 */
			public com.google.protobuf.ByteString
			getIdBytes() {
				java.lang.Object ref = id_;
				if (ref instanceof java.lang.String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(java.lang.String) ref);
					id_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			@java.lang.Override
			public final boolean isInitialized() {
				byte isInitialized = memoizedIsInitialized;
				if (isInitialized == 1) return true;
				if (isInitialized == 0) return false;

				memoizedIsInitialized = 1;
				return true;
			}

			@java.lang.Override
			public void writeTo(com.google.protobuf.CodedOutputStream output) {
				if (!getAddressBytes().isEmpty()) {
					com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
				}
				if (!getPortBytes().isEmpty()) {
					com.google.protobuf.GeneratedMessageV3.writeString(output, 2, port_);
				}
				if (!getIdBytes().isEmpty()) {
					com.google.protobuf.GeneratedMessageV3.writeString(output, 3, id_);
				}
				unknownFields.writeTo(output);
			}

			@java.lang.Override
			public int getSerializedSize() {
				int size = memoizedSize;
				if (size != -1) return size;

				size = 0;
				if (!getAddressBytes().isEmpty()) {
					size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
				}
				if (!getPortBytes().isEmpty()) {
					size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, port_);
				}
				if (!getIdBytes().isEmpty()) {
					size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, id_);
				}
				size += unknownFields.getSerializedSize();
				memoizedSize = size;
				return size;
			}

			@java.lang.Override
			public boolean equals(final java.lang.Object obj) {
				if (obj == this) {
					return true;
				}
				if (!(obj instanceof proto.MessagesProtos.ClientRequest.Socket)) {
					return super.equals(obj);
				}
				proto.MessagesProtos.ClientRequest.Socket other = (proto.MessagesProtos.ClientRequest.Socket) obj;

				boolean result = true;
				result = result && getAddress()
						.equals(other.getAddress());
				result = result && getPort()
						.equals(other.getPort());
				result = result && getId()
						.equals(other.getId());
				result = result && unknownFields.equals(other.unknownFields);
				return result;
			}

			@java.lang.Override
			public int hashCode() {
				if (memoizedHashCode != 0) {
					return memoizedHashCode;
				}
				int hash = 41;
				hash = (19 * hash) + getDescriptor().hashCode();
				hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
				hash = (53 * hash) + getAddress().hashCode();
				hash = (37 * hash) + PORT_FIELD_NUMBER;
				hash = (53 * hash) + getPort().hashCode();
				hash = (37 * hash) + ID_FIELD_NUMBER;
				hash = (53 * hash) + getId().hashCode();
				hash = (29 * hash) + unknownFields.hashCode();
				memoizedHashCode = hash;
				return hash;
			}

			@java.lang.Override
			public Builder newBuilderForType() {
				return newBuilder();
			}

			@java.lang.Override
			public Builder toBuilder() {
				return this == DEFAULT_INSTANCE
						? new Builder() : new Builder().mergeFrom(this);
			}

			@java.lang.Override
			protected Builder newBuilderForType(
					com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				Builder builder = new Builder(parent);
				return builder;
			}

			@java.lang.Override
			public com.google.protobuf.Parser<Socket> getParserForType() {
				return PARSER;
			}

			@java.lang.Override
			public proto.MessagesProtos.ClientRequest.Socket getDefaultInstanceForType() {
				return DEFAULT_INSTANCE;
			}

			/**
			 * Protobuf type {@code proto.ClientRequest.Socket}
			 */
			public static final class Builder extends
					com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
					// @@protoc_insertion_point(builder_implements:proto.ClientRequest.Socket)
					proto.MessagesProtos.ClientRequest.SocketOrBuilder {
				private java.lang.Object address_ = "";
				private java.lang.Object port_ = "";
				private java.lang.Object id_ = "";

				// Construct using proto.MessagesProtos.ClientRequest.Socket.newBuilder()
				private Builder() {
					maybeForceBuilderInitialization();
				}

				private Builder(
						com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
					super(parent);
					maybeForceBuilderInitialization();
				}

				public static final com.google.protobuf.Descriptors.Descriptor
				getDescriptor() {
					return proto.MessagesProtos.internal_static_proto_ClientRequest_Socket_descriptor;
				}

				@java.lang.Override
				protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
				internalGetFieldAccessorTable() {
					return proto.MessagesProtos.internal_static_proto_ClientRequest_Socket_fieldAccessorTable
							.ensureFieldAccessorsInitialized(
									proto.MessagesProtos.ClientRequest.Socket.class, proto.MessagesProtos.ClientRequest.Socket.Builder.class);
				}

				private void maybeForceBuilderInitialization() {
					if (com.google.protobuf.GeneratedMessageV3
							.alwaysUseFieldBuilders) {
					}
				}

				@java.lang.Override
				public Builder clear() {
					super.clear();
					address_ = "";

					port_ = "";

					id_ = "";

					return this;
				}

				@java.lang.Override
				public com.google.protobuf.Descriptors.Descriptor
				getDescriptorForType() {
					return proto.MessagesProtos.internal_static_proto_ClientRequest_Socket_descriptor;
				}

				@java.lang.Override
				public proto.MessagesProtos.ClientRequest.Socket getDefaultInstanceForType() {
					return proto.MessagesProtos.ClientRequest.Socket.getDefaultInstance();
				}

				@java.lang.Override
				public proto.MessagesProtos.ClientRequest.Socket build() {
					proto.MessagesProtos.ClientRequest.Socket result = buildPartial();
					if (!result.isInitialized()) {
						throw newUninitializedMessageException(result);
					}
					return result;
				}

				@java.lang.Override
				public proto.MessagesProtos.ClientRequest.Socket buildPartial() {
					proto.MessagesProtos.ClientRequest.Socket result = new proto.MessagesProtos.ClientRequest.Socket(this);
					result.address_ = address_;
					result.port_ = port_;
					result.id_ = id_;
					onBuilt();
					return result;
				}

				@java.lang.Override
				public Builder clone() {
					return (Builder) super.clone();
				}

				@java.lang.Override
				public Builder setField(
						com.google.protobuf.Descriptors.FieldDescriptor field,
						java.lang.Object value) {
					return (Builder) super.setField(field, value);
				}

				@java.lang.Override
				public Builder clearField(
						com.google.protobuf.Descriptors.FieldDescriptor field) {
					return (Builder) super.clearField(field);
				}

				@java.lang.Override
				public Builder clearOneof(
						com.google.protobuf.Descriptors.OneofDescriptor oneof) {
					return (Builder) super.clearOneof(oneof);
				}

				@java.lang.Override
				public Builder setRepeatedField(
						com.google.protobuf.Descriptors.FieldDescriptor field,
						int index, java.lang.Object value) {
					return (Builder) super.setRepeatedField(field, index, value);
				}

				@java.lang.Override
				public Builder addRepeatedField(
						com.google.protobuf.Descriptors.FieldDescriptor field,
						java.lang.Object value) {
					return (Builder) super.addRepeatedField(field, value);
				}

				@java.lang.Override
				public Builder mergeFrom(com.google.protobuf.Message other) {
					if (other instanceof proto.MessagesProtos.ClientRequest.Socket) {
						return mergeFrom((proto.MessagesProtos.ClientRequest.Socket) other);
					} else {
						super.mergeFrom(other);
						return this;
					}
				}

				public Builder mergeFrom(proto.MessagesProtos.ClientRequest.Socket other) {
					if (other == proto.MessagesProtos.ClientRequest.Socket.getDefaultInstance()) return this;
					if (!other.getAddress().isEmpty()) {
						address_ = other.address_;
						onChanged();
					}
					if (!other.getPort().isEmpty()) {
						port_ = other.port_;
						onChanged();
					}
					if (!other.getId().isEmpty()) {
						id_ = other.id_;
						onChanged();
					}
					this.mergeUnknownFields(other.unknownFields);
					onChanged();
					return this;
				}

				@java.lang.Override
				public final boolean isInitialized() {
					return true;
				}

				@java.lang.Override
				public Builder mergeFrom(
						com.google.protobuf.CodedInputStream input,
						com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
					proto.MessagesProtos.ClientRequest.Socket parsedMessage = null;
					try {
						parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
					} catch (com.google.protobuf.InvalidProtocolBufferException e) {
						parsedMessage = (proto.MessagesProtos.ClientRequest.Socket) e.getUnfinishedMessage();
						throw e.unwrapIOException();
					} finally {
						if (parsedMessage != null) {
							mergeFrom(parsedMessage);
						}
					}
					return this;
				}

				/**
				 * <code>string address = 1;</code>
				 */
				public java.lang.String getAddress() {
					java.lang.Object ref = address_;
					if (!(ref instanceof java.lang.String)) {
						com.google.protobuf.ByteString bs =
								(com.google.protobuf.ByteString) ref;
						java.lang.String s = bs.toStringUtf8();
						address_ = s;
						return s;
					} else {
						return (java.lang.String) ref;
					}
				}

				/**
				 * <code>string address = 1;</code>
				 */
				public Builder setAddress(
						java.lang.String value) {
					if (value == null) {
						throw new NullPointerException();
					}

					address_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>string address = 1;</code>
				 */
				public com.google.protobuf.ByteString
				getAddressBytes() {
					java.lang.Object ref = address_;
					if (ref instanceof String) {
						com.google.protobuf.ByteString b =
								com.google.protobuf.ByteString.copyFromUtf8(
										(java.lang.String) ref);
						address_ = b;
						return b;
					} else {
						return (com.google.protobuf.ByteString) ref;
					}
				}

				/**
				 * <code>string address = 1;</code>
				 */
				public Builder setAddressBytes(
						com.google.protobuf.ByteString value) {
					if (value == null) {
						throw new NullPointerException();
					}
					checkByteStringIsUtf8(value);

					address_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>string address = 1;</code>
				 */
				public Builder clearAddress() {

					address_ = getDefaultInstance().getAddress();
					onChanged();
					return this;
				}

				/**
				 * <code>string port = 2;</code>
				 */
				public java.lang.String getPort() {
					java.lang.Object ref = port_;
					if (!(ref instanceof java.lang.String)) {
						com.google.protobuf.ByteString bs =
								(com.google.protobuf.ByteString) ref;
						java.lang.String s = bs.toStringUtf8();
						port_ = s;
						return s;
					} else {
						return (java.lang.String) ref;
					}
				}

				/**
				 * <code>string port = 2;</code>
				 */
				public Builder setPort(
						java.lang.String value) {
					if (value == null) {
						throw new NullPointerException();
					}

					port_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>string port = 2;</code>
				 */
				public com.google.protobuf.ByteString
				getPortBytes() {
					java.lang.Object ref = port_;
					if (ref instanceof String) {
						com.google.protobuf.ByteString b =
								com.google.protobuf.ByteString.copyFromUtf8(
										(java.lang.String) ref);
						port_ = b;
						return b;
					} else {
						return (com.google.protobuf.ByteString) ref;
					}
				}

				/**
				 * <code>string port = 2;</code>
				 */
				public Builder setPortBytes(
						com.google.protobuf.ByteString value) {
					if (value == null) {
						throw new NullPointerException();
					}
					checkByteStringIsUtf8(value);

					port_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>string port = 2;</code>
				 */
				public Builder clearPort() {

					port_ = getDefaultInstance().getPort();
					onChanged();
					return this;
				}

				/**
				 * <code>string id = 3;</code>
				 */
				public java.lang.String getId() {
					java.lang.Object ref = id_;
					if (!(ref instanceof java.lang.String)) {
						com.google.protobuf.ByteString bs =
								(com.google.protobuf.ByteString) ref;
						java.lang.String s = bs.toStringUtf8();
						id_ = s;
						return s;
					} else {
						return (java.lang.String) ref;
					}
				}

				/**
				 * <code>string id = 3;</code>
				 */
				public Builder setId(
						java.lang.String value) {
					if (value == null) {
						throw new NullPointerException();
					}

					id_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>string id = 3;</code>
				 */
				public com.google.protobuf.ByteString
				getIdBytes() {
					java.lang.Object ref = id_;
					if (ref instanceof String) {
						com.google.protobuf.ByteString b =
								com.google.protobuf.ByteString.copyFromUtf8(
										(java.lang.String) ref);
						id_ = b;
						return b;
					} else {
						return (com.google.protobuf.ByteString) ref;
					}
				}

				/**
				 * <code>string id = 3;</code>
				 */
				public Builder setIdBytes(
						com.google.protobuf.ByteString value) {
					if (value == null) {
						throw new NullPointerException();
					}
					checkByteStringIsUtf8(value);

					id_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>string id = 3;</code>
				 */
				public Builder clearId() {

					id_ = getDefaultInstance().getId();
					onChanged();
					return this;
				}

				@java.lang.Override
				public final Builder setUnknownFields(
						final com.google.protobuf.UnknownFieldSet unknownFields) {
					return super.setUnknownFieldsProto3(unknownFields);
				}

				@java.lang.Override
				public final Builder mergeUnknownFields(
						final com.google.protobuf.UnknownFieldSet unknownFields) {
					return super.mergeUnknownFields(unknownFields);
				}


				// @@protoc_insertion_point(builder_scope:proto.ClientRequest.Socket)
			}

		}

		/**
		 * Protobuf type {@code proto.ClientRequest}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:proto.ClientRequest)
				proto.MessagesProtos.ClientRequestOrBuilder {
			private int type_ = 0;
			private java.lang.Object arg_ = "";
			private proto.MessagesProtos.ClientRequest.Socket sock_ = null;
			private com.google.protobuf.SingleFieldBuilderV3<
					proto.MessagesProtos.ClientRequest.Socket, proto.MessagesProtos.ClientRequest.Socket.Builder, proto.MessagesProtos.ClientRequest.SocketOrBuilder> sockBuilder_;

			// Construct using proto.MessagesProtos.ClientRequest.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return proto.MessagesProtos.internal_static_proto_ClientRequest_descriptor;
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internalGetFieldAccessorTable() {
				return proto.MessagesProtos.internal_static_proto_ClientRequest_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								proto.MessagesProtos.ClientRequest.class, proto.MessagesProtos.ClientRequest.Builder.class);
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3
						.alwaysUseFieldBuilders) {
				}
			}

			@java.lang.Override
			public Builder clear() {
				super.clear();
				type_ = 0;

				arg_ = "";

				if (sockBuilder_ == null) {
					sock_ = null;
				} else {
					sock_ = null;
					sockBuilder_ = null;
				}
				return this;
			}

			@java.lang.Override
			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return proto.MessagesProtos.internal_static_proto_ClientRequest_descriptor;
			}

			@java.lang.Override
			public proto.MessagesProtos.ClientRequest getDefaultInstanceForType() {
				return proto.MessagesProtos.ClientRequest.getDefaultInstance();
			}

			@java.lang.Override
			public proto.MessagesProtos.ClientRequest build() {
				proto.MessagesProtos.ClientRequest result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@java.lang.Override
			public proto.MessagesProtos.ClientRequest buildPartial() {
				proto.MessagesProtos.ClientRequest result = new proto.MessagesProtos.ClientRequest(this);
				result.type_ = type_;
				result.arg_ = arg_;
				if (sockBuilder_ == null) {
					result.sock_ = sock_;
				} else {
					result.sock_ = sockBuilder_.build();
				}
				onBuilt();
				return result;
			}

			@java.lang.Override
			public Builder clone() {
				return (Builder) super.clone();
			}

			@java.lang.Override
			public Builder setField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					java.lang.Object value) {
				return (Builder) super.setField(field, value);
			}

			@java.lang.Override
			public Builder clearField(
					com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			@java.lang.Override
			public Builder clearOneof(
					com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			@java.lang.Override
			public Builder setRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					int index, java.lang.Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			@java.lang.Override
			public Builder addRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					java.lang.Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof proto.MessagesProtos.ClientRequest) {
					return mergeFrom((proto.MessagesProtos.ClientRequest) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(proto.MessagesProtos.ClientRequest other) {
				if (other == proto.MessagesProtos.ClientRequest.getDefaultInstance()) return this;
				if (other.type_ != 0) {
					setTypeValue(other.getTypeValue());
				}
				if (!other.getArg().isEmpty()) {
					arg_ = other.arg_;
					onChanged();
				}
				if (other.hasSock()) {
					mergeSock(other.getSock());
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@java.lang.Override
			public final boolean isInitialized() {
				return true;
			}

			@java.lang.Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
				proto.MessagesProtos.ClientRequest parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (proto.MessagesProtos.ClientRequest) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			/**
			 * <code>.proto.ClientRequest.MessageType type = 1;</code>
			 */
			public int getTypeValue() {
				return type_;
			}

			/**
			 * <code>.proto.ClientRequest.MessageType type = 1;</code>
			 */
			public Builder setTypeValue(int value) {
				type_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>.proto.ClientRequest.MessageType type = 1;</code>
			 */
			public proto.MessagesProtos.ClientRequest.MessageType getType() {
				@SuppressWarnings("deprecation")
				proto.MessagesProtos.ClientRequest.MessageType result = proto.MessagesProtos.ClientRequest.MessageType.valueOf(type_);
				return result == null ? proto.MessagesProtos.ClientRequest.MessageType.UNRECOGNIZED : result;
			}

			/**
			 * <code>.proto.ClientRequest.MessageType type = 1;</code>
			 */
			public Builder setType(proto.MessagesProtos.ClientRequest.MessageType value) {
				if (value == null) {
					throw new NullPointerException();
				}

				type_ = value.getNumber();
				onChanged();
				return this;
			}

			/**
			 * <code>.proto.ClientRequest.MessageType type = 1;</code>
			 */
			public Builder clearType() {

				type_ = 0;
				onChanged();
				return this;
			}

			/**
			 * <code>string arg = 2;</code>
			 */
			public java.lang.String getArg() {
				java.lang.Object ref = arg_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					arg_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string arg = 2;</code>
			 */
			public Builder setArg(
					java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				arg_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string arg = 2;</code>
			 */
			public com.google.protobuf.ByteString
			getArgBytes() {
				java.lang.Object ref = arg_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(java.lang.String) ref);
					arg_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string arg = 2;</code>
			 */
			public Builder setArgBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				arg_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string arg = 2;</code>
			 */
			public Builder clearArg() {

				arg_ = getDefaultInstance().getArg();
				onChanged();
				return this;
			}

			/**
			 * <code>.proto.ClientRequest.Socket sock = 3;</code>
			 */
			public boolean hasSock() {
				return sockBuilder_ != null || sock_ != null;
			}

			/**
			 * <code>.proto.ClientRequest.Socket sock = 3;</code>
			 */
			public proto.MessagesProtos.ClientRequest.Socket getSock() {
				if (sockBuilder_ == null) {
					return sock_ == null ? proto.MessagesProtos.ClientRequest.Socket.getDefaultInstance() : sock_;
				} else {
					return sockBuilder_.getMessage();
				}
			}

			/**
			 * <code>.proto.ClientRequest.Socket sock = 3;</code>
			 */
			public Builder setSock(proto.MessagesProtos.ClientRequest.Socket value) {
				if (sockBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					sock_ = value;
					onChanged();
				} else {
					sockBuilder_.setMessage(value);
				}

				return this;
			}

			/**
			 * <code>.proto.ClientRequest.Socket sock = 3;</code>
			 */
			public Builder setSock(
					proto.MessagesProtos.ClientRequest.Socket.Builder builderForValue) {
				if (sockBuilder_ == null) {
					sock_ = builderForValue.build();
					onChanged();
				} else {
					sockBuilder_.setMessage(builderForValue.build());
				}

				return this;
			}

			/**
			 * <code>.proto.ClientRequest.Socket sock = 3;</code>
			 */
			public Builder mergeSock(proto.MessagesProtos.ClientRequest.Socket value) {
				if (sockBuilder_ == null) {
					if (sock_ != null) {
						sock_ =
								proto.MessagesProtos.ClientRequest.Socket.newBuilder(sock_).mergeFrom(value).buildPartial();
					} else {
						sock_ = value;
					}
					onChanged();
				} else {
					sockBuilder_.mergeFrom(value);
				}

				return this;
			}

			/**
			 * <code>.proto.ClientRequest.Socket sock = 3;</code>
			 */
			public Builder clearSock() {
				if (sockBuilder_ == null) {
					sock_ = null;
					onChanged();
				} else {
					sock_ = null;
					sockBuilder_ = null;
				}

				return this;
			}

			/**
			 * <code>.proto.ClientRequest.Socket sock = 3;</code>
			 */
			public proto.MessagesProtos.ClientRequest.Socket.Builder getSockBuilder() {

				onChanged();
				return getSockFieldBuilder().getBuilder();
			}

			/**
			 * <code>.proto.ClientRequest.Socket sock = 3;</code>
			 */
			public proto.MessagesProtos.ClientRequest.SocketOrBuilder getSockOrBuilder() {
				if (sockBuilder_ != null) {
					return sockBuilder_.getMessageOrBuilder();
				} else {
					return sock_ == null ?
							proto.MessagesProtos.ClientRequest.Socket.getDefaultInstance() : sock_;
				}
			}

			/**
			 * <code>.proto.ClientRequest.Socket sock = 3;</code>
			 */
			private com.google.protobuf.SingleFieldBuilderV3<
					proto.MessagesProtos.ClientRequest.Socket, proto.MessagesProtos.ClientRequest.Socket.Builder, proto.MessagesProtos.ClientRequest.SocketOrBuilder>
			getSockFieldBuilder() {
				if (sockBuilder_ == null) {
					sockBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
							proto.MessagesProtos.ClientRequest.Socket, proto.MessagesProtos.ClientRequest.Socket.Builder, proto.MessagesProtos.ClientRequest.SocketOrBuilder>(
							getSock(),
							getParentForChildren(),
							isClean());
					sock_ = null;
				}
				return sockBuilder_;
			}

			@java.lang.Override
			public final Builder setUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFieldsProto3(unknownFields);
			}

			@java.lang.Override
			public final Builder mergeUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}


			// @@protoc_insertion_point(builder_scope:proto.ClientRequest)
		}

	}

	/**
	 * Protobuf type {@code proto.ServerResponse}
	 */
	public static final class ServerResponse extends
			com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:proto.ServerResponse)
			ServerResponseOrBuilder {
		public static final int ACK_FIELD_NUMBER = 1;
		public static final int ARGS_FIELD_NUMBER = 2;
		private static final long serialVersionUID = 0L;
		// @@protoc_insertion_point(class_scope:proto.ServerResponse)
		private static final proto.MessagesProtos.ServerResponse DEFAULT_INSTANCE;
		private static final com.google.protobuf.Parser<ServerResponse>
				PARSER = new com.google.protobuf.AbstractParser<ServerResponse>() {
			@java.lang.Override
			public ServerResponse parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new ServerResponse(input, extensionRegistry);
			}
		};

		static {
			DEFAULT_INSTANCE = new proto.MessagesProtos.ServerResponse();
		}

		private int bitField0_;
		private boolean ack_;
		private com.google.protobuf.LazyStringList args_;
		private byte memoizedIsInitialized = -1;

		// Use ServerResponse.newBuilder() to construct.
		private ServerResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private ServerResponse() {
			ack_ = false;
			args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
		}

		private ServerResponse(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new java.lang.NullPointerException();
			}
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields =
					com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						case 8: {

							ack_ = input.readBool();
							break;
						}
						case 18: {
							java.lang.String s = input.readStringRequireUtf8();
							if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
								args_ = new com.google.protobuf.LazyStringArrayList();
								mutable_bitField0_ |= 0x00000002;
							}
							args_.add(s);
							break;
						}
						default: {
							if (!parseUnknownFieldProto3(
									input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e).setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
					args_ = args_.getUnmodifiableView();
				}
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return proto.MessagesProtos.internal_static_proto_ServerResponse_descriptor;
		}

		public static proto.MessagesProtos.ServerResponse parseFrom(
				java.nio.ByteBuffer data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static proto.MessagesProtos.ServerResponse parseFrom(
				java.nio.ByteBuffer data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static proto.MessagesProtos.ServerResponse parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static proto.MessagesProtos.ServerResponse parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static proto.MessagesProtos.ServerResponse parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static proto.MessagesProtos.ServerResponse parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static proto.MessagesProtos.ServerResponse parseFrom(java.io.InputStream input) {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static proto.MessagesProtos.ServerResponse parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static proto.MessagesProtos.ServerResponse parseDelimitedFrom(java.io.InputStream input) {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input);
		}

		public static proto.MessagesProtos.ServerResponse parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static proto.MessagesProtos.ServerResponse parseFrom(
				com.google.protobuf.CodedInputStream input) {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static proto.MessagesProtos.ServerResponse parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(proto.MessagesProtos.ServerResponse prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		public static proto.MessagesProtos.ServerResponse getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		public static com.google.protobuf.Parser<ServerResponse> parser() {
			return PARSER;
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet
		getUnknownFields() {
			return this.unknownFields;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
		internalGetFieldAccessorTable() {
			return proto.MessagesProtos.internal_static_proto_ServerResponse_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							proto.MessagesProtos.ServerResponse.class, proto.MessagesProtos.ServerResponse.Builder.class);
		}

		/**
		 * <code>bool ack = 1;</code>
		 */
		public boolean getAck() {
			return ack_;
		}

		/**
		 * <code>repeated string args = 2;</code>
		 */
		public com.google.protobuf.ProtocolStringList
		getArgsList() {
			return args_;
		}

		/**
		 * <code>repeated string args = 2;</code>
		 */
		public int getArgsCount() {
			return args_.size();
		}

		/**
		 * <code>repeated string args = 2;</code>
		 */
		public java.lang.String getArgs(int index) {
			return args_.get(index);
		}

		/**
		 * <code>repeated string args = 2;</code>
		 */
		public com.google.protobuf.ByteString
		getArgsBytes(int index) {
			return args_.getByteString(index);
		}

		@java.lang.Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1) return true;
			if (isInitialized == 0) return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@java.lang.Override
		public void writeTo(com.google.protobuf.CodedOutputStream output) {
			if (ack_ != false) {
				output.writeBool(1, ack_);
			}
			for (int i = 0; i < args_.size(); i++) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 2, args_.getRaw(i));
			}
			unknownFields.writeTo(output);
		}

		@java.lang.Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1) return size;

			size = 0;
			if (ack_ != false) {
				size += com.google.protobuf.CodedOutputStream
						.computeBoolSize(1, ack_);
			}
			{
				int dataSize = 0;
				for (int i = 0; i < args_.size(); i++) {
					dataSize += computeStringSizeNoTag(args_.getRaw(i));
				}
				size += dataSize;
				size += 1 * getArgsList().size();
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof proto.MessagesProtos.ServerResponse)) {
				return super.equals(obj);
			}
			proto.MessagesProtos.ServerResponse other = (proto.MessagesProtos.ServerResponse) obj;

			boolean result = true;
			result = result && (getAck()
					== other.getAck());
			result = result && getArgsList()
					.equals(other.getArgsList());
			result = result && unknownFields.equals(other.unknownFields);
			return result;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + ACK_FIELD_NUMBER;
			hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
					getAck());
			if (getArgsCount() > 0) {
				hash = (37 * hash) + ARGS_FIELD_NUMBER;
				hash = (53 * hash) + getArgsList().hashCode();
			}
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		@java.lang.Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		@java.lang.Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE
					? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<ServerResponse> getParserForType() {
			return PARSER;
		}

		@java.lang.Override
		public proto.MessagesProtos.ServerResponse getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

		/**
		 * Protobuf type {@code proto.ServerResponse}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:proto.ServerResponse)
				proto.MessagesProtos.ServerResponseOrBuilder {
			private int bitField0_;
			private boolean ack_;
			private com.google.protobuf.LazyStringList args_ = com.google.protobuf.LazyStringArrayList.EMPTY;

			// Construct using proto.MessagesProtos.ServerResponse.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return proto.MessagesProtos.internal_static_proto_ServerResponse_descriptor;
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internalGetFieldAccessorTable() {
				return proto.MessagesProtos.internal_static_proto_ServerResponse_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								proto.MessagesProtos.ServerResponse.class, proto.MessagesProtos.ServerResponse.Builder.class);
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3
						.alwaysUseFieldBuilders) {
				}
			}

			@java.lang.Override
			public Builder clear() {
				super.clear();
				ack_ = false;

				args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000002);
				return this;
			}

			@java.lang.Override
			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return proto.MessagesProtos.internal_static_proto_ServerResponse_descriptor;
			}

			@java.lang.Override
			public proto.MessagesProtos.ServerResponse getDefaultInstanceForType() {
				return proto.MessagesProtos.ServerResponse.getDefaultInstance();
			}

			@java.lang.Override
			public proto.MessagesProtos.ServerResponse build() {
				proto.MessagesProtos.ServerResponse result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@java.lang.Override
			public proto.MessagesProtos.ServerResponse buildPartial() {
				proto.MessagesProtos.ServerResponse result = new proto.MessagesProtos.ServerResponse(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				result.ack_ = ack_;
				if (((bitField0_ & 0x00000002) == 0x00000002)) {
					args_ = args_.getUnmodifiableView();
					bitField0_ = (bitField0_ & ~0x00000002);
				}
				result.args_ = args_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			@java.lang.Override
			public Builder clone() {
				return (Builder) super.clone();
			}

			@java.lang.Override
			public Builder setField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					java.lang.Object value) {
				return (Builder) super.setField(field, value);
			}

			@java.lang.Override
			public Builder clearField(
					com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			@java.lang.Override
			public Builder clearOneof(
					com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			@java.lang.Override
			public Builder setRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					int index, java.lang.Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			@java.lang.Override
			public Builder addRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					java.lang.Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof proto.MessagesProtos.ServerResponse) {
					return mergeFrom((proto.MessagesProtos.ServerResponse) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(proto.MessagesProtos.ServerResponse other) {
				if (other == proto.MessagesProtos.ServerResponse.getDefaultInstance()) return this;
				if (other.getAck() != false) {
					setAck(other.getAck());
				}
				if (!other.args_.isEmpty()) {
					if (args_.isEmpty()) {
						args_ = other.args_;
						bitField0_ = (bitField0_ & ~0x00000002);
					} else {
						ensureArgsIsMutable();
						args_.addAll(other.args_);
					}
					onChanged();
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@java.lang.Override
			public final boolean isInitialized() {
				return true;
			}

			@java.lang.Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
				proto.MessagesProtos.ServerResponse parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (proto.MessagesProtos.ServerResponse) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			/**
			 * <code>bool ack = 1;</code>
			 */
			public boolean getAck() {
				return ack_;
			}

			/**
			 * <code>bool ack = 1;</code>
			 */
			public Builder setAck(boolean value) {

				ack_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>bool ack = 1;</code>
			 */
			public Builder clearAck() {

				ack_ = false;
				onChanged();
				return this;
			}

			private void ensureArgsIsMutable() {
				if (!((bitField0_ & 0x00000002) == 0x00000002)) {
					args_ = new com.google.protobuf.LazyStringArrayList(args_);
					bitField0_ |= 0x00000002;
				}
			}

			/**
			 * <code>repeated string args = 2;</code>
			 */
			public com.google.protobuf.ProtocolStringList
			getArgsList() {
				return args_.getUnmodifiableView();
			}

			/**
			 * <code>repeated string args = 2;</code>
			 */
			public int getArgsCount() {
				return args_.size();
			}

			/**
			 * <code>repeated string args = 2;</code>
			 */
			public java.lang.String getArgs(int index) {
				return args_.get(index);
			}

			/**
			 * <code>repeated string args = 2;</code>
			 */
			public com.google.protobuf.ByteString
			getArgsBytes(int index) {
				return args_.getByteString(index);
			}

			/**
			 * <code>repeated string args = 2;</code>
			 */
			public Builder setArgs(
					int index, java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureArgsIsMutable();
				args_.set(index, value);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated string args = 2;</code>
			 */
			public Builder addArgs(
					java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureArgsIsMutable();
				args_.add(value);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated string args = 2;</code>
			 */
			public Builder addAllArgs(
					java.lang.Iterable<java.lang.String> values) {
				ensureArgsIsMutable();
				com.google.protobuf.AbstractMessageLite.Builder.addAll(
						values, args_);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated string args = 2;</code>
			 */
			public Builder clearArgs() {
				args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000002);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated string args = 2;</code>
			 */
			public Builder addArgsBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);
				ensureArgsIsMutable();
				args_.add(value);
				onChanged();
				return this;
			}

			@java.lang.Override
			public final Builder setUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFieldsProto3(unknownFields);
			}

			@java.lang.Override
			public final Builder mergeUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}


			// @@protoc_insertion_point(builder_scope:proto.ServerResponse)
		}

	}

	// @@protoc_insertion_point(outer_class_scope)
}
